### ISSUE TITLE
After installation for Windows - no settings are shown (or can be provided) for Databricks

### ISSUE THREAD

**Issue by VolkerBu** [mullerpeter/databricks-grafana#118]
**Describe the bug**
After the installation to Windows "Databricks" is shown as "Installed" under Connections. After "Add new data source" the new connection "mullerpeter-databricks-datasource" was created. But in the settings tab nothing is shown or can be changed. (but this works for other connections, MySQL etc.).

**To Reproduce**
Windows Grafana OSS v11.6.1 >= 10.4   (and works with conections to MySQL)
1. Executed "Install the Data Source"
2. Unzip to "C:\Program Files\GrafanaLabs\grafana\public\app\plugins\datasource"
3. Edit the grafana configuration "C:\Program Files\GrafanaLabs\grafana\conf\custom.ini"
  [plugins]
allow_loading_unsigned_plugins = mullerpeter-databricks-datasource
4. Restarting Grafana 
5. Add "Add new data source"   with "Databricks"

**Expected behavior**
To be able to add the settings to "mullerpeter-databricks-datasource". But settings is blank - doesn't allow to enter any input

**Screenshots**

<img width="376" alt="Image" src="https://github.com/user-attachments/assets/1208b922-2100-4578-b7a2-19fa06b7fae7" />

<img width="376" alt="Image" src="https://github.com/user-attachments/assets/0f9346df-bee4-4651-b069-32e59e03ad77" />

**Environment:**
Plugin Version:
Grafana Version:

**Comment by VolkerBu** [comment]
Hi Peter,

Yep - looks like you are right.




***@***.***


Von: Peter Müller ***@***.***>
Gesendet: Mittwoch, 11. Juni 2025 11:49
An: mullerpeter/databricks-grafana ***@***.***>
Cc: Volker Buschmann ***@***.***>; Mention ***@***.***>
Betreff: Re: [mullerpeter/databricks-grafana] After installation for Windows - no settings are shown (or can be provided) for Databricks (Issue #118)

[https://avatars.githubusercontent.com/u/6986867?s=20&v=4]mullerpeter left a comment (mullerpeter/databricks-grafana#118)<https://github.com/mullerpeter/databricks-grafana/issues/118#issuecomment-2961997354>

Hi @VolkerBu<https://github.com/VolkerBu>

Thanks for opening the issue. I'll try to setup Grafana on a Windows machine to reproduce the error.

Empty settings page usually happens because of some JS libs not loading correctly. There should be an error in the JS console of the browser. Can you check that and copy the error here?

-

**Comment by mullerpeter** [comment]
Hello @VolkerBu 

I currently don't have access to a windows machine to reproduce the error, so this might take some time.
Can you copy the error you see in the JS console of the browser here in a comment?

**Comment by mullerpeter** [comment]
As an alternative you could try to provision the datasource using yaml as described [here](https://grafana.com/docs/grafana/latest/administration/provisioning/) (or [here](https://github.com/grafana/grafana/tree/main/conf)) using a datasource yaml file according to the documentation.

```yaml
datasources:
  - name: Databricks
    type: mullerpeter-databricks-datasource
    isDefault: true
    jsonData:
      hostname: XXX.cloud.databricks.com
      path: sql/1.0/endpoints/XXX
      port: "443"
      authenticationMethod: dsn (=PAT) | m2m | oauth2_client_credentials | oauth2_pass_through
      clientId: ...
      externalCredentialsUrl: ...
      oauthScopes: api,read
      timeInterval: 1m
      maxOpenConns: "0"
      maxIdleConns: "0"
      connMaxLifetime: "3600"
      connMaxIdleTime: "3600"
      retries: "3"
      retryBackoff: "1"
      maxRetryDuration: "60"
      timeout: "60"
      maxRows: "10000"
      defaultQueryFormat: table | time_series
      defaultEditorMode: builder | code
    secureJsonData:
      clientSecret: ...
      token: ...
```
